services:
  - type: web
    name: ramstores-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:10000 app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
